#撒啊啊啊
server:
  port: 7002
eureka:
  instance:
    hostname: eureka7002.com
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
spring:
  rabbitmq:
    host: 192.168.80.128
    port: 5672
    username: root
    password: 123456