server:
  port: 80
spring:
  application:
    name: cloud-consumer-service
  rabbitmq:
    host: 192.168.80.128
    port: 5672
    username: root
    password: 123456
  cloud:
    consul:
      port: 8500
      host: ${spring.rabbitmq.host}
      discovery:
        service-name: ${spring.application.name}
        ip-address: 192.168.36.179
        health-check-url: http://${spring.cloud.consul.discovery.ip-address}:${server.port}/actuator/health

